name : CICD with Terraform
on:
 push:
  branch:
  - main
env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
 TF_STATE_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
 PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_ACCESS_KEY }}
 PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_ACCESS_PUBLIC }}
 AWS_REGION: ap-southeast-1

jobs:
 deploy-infra:
  runs-on: ubuntu-lastest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: setup Terraform
    uses: hashicorp/setup-terraform@v1
    with:
     terraform_wrapper: false
  - name: Terraform init
    id: init
    run: terraform init -backend-config="bucket=$TFTF_STATE_BUCKET_NAME" -backend-config="region=ap-southeast-1"
    working-directory: ./terraform
  - name: Terraform Plan
    id: plan
    run: |-
     terraform plan \
     -var="region=ap-southeast-1" \
     -var="public_key=$PUBLIC_SSH_KEY" \
     -var="private_key"=$PRIVATE_SSH_KEY" \
     -var="key_name=deployer-key" \
     -out=PLAN
    working-directory: ./terraform
  - name: Terraform Apply
    if: applu
    run: terraform apply PLAN
    working-directory: ./terrform