name: CICD with Terraform

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
  TF_STATE_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_ACCESS_KEY }}
  PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_ACCESS_PUBLIC }}
  AWS_REGION: ap-southeast-1

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-ip.outputs.SERVER_PUBLIC_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$TF_STATE_BUCKET_NAME" -backend-config="region=$AWS_REGION"
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="region=ap-southeast-1" \
            -var="private_key=${{ secrets.AWS_SSH_ACCESS_KEY }}" \
            -var="public_key=${{ secrets.AWS_SSH_ACCESS_PUBLIC }}" \
            -out=PLAN
        working-directory: ./terraform
      
      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve PLAN
        env: 
          PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_ACCESS_KEY }}
          PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_ACCESS_PUBLIC }}
        working-directory: ./terraform
        id: apply

      - name: Set output variables
        run: echo "SERVER_PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform
        id: set-ip

  deploy-app:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - env:
          SERVER_PUBLIC_IP: ${{needs.deploy-infra.outputs.output1}}
        run: echo "$SERVER_PUBLIC_IP"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, push docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: devops-node-app
          IMAGE_TAG: ${{ github.sha }}
          AWS_DEFAULT_REGION: ap-southeast-1
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./nodeapp
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Docker Deploy image to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ env.SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.PRIVATE_SSH_KEY }}
          envs: PRIVATE_SSH_KEY,REGISTRY,REPOSITORY,IMAGE_TAG,ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,TF_STATE_BUCKET_NAME,AWS_DEFAULT_REGION,AWS_REGION
          script: |
            sudo apt update
            sudo apt install -y docker.io awscli
            $(aws ecr get-login-password --region ap-southeast-1 | sudo docker login --username AWS --password-stdin $REGISTRY)
            sudo docker stop myappcontainer || true
            sudo docker rm myappcontainer || true
            sudo docker pull $REGISTRY/$REPOSITORY:$IMAGE_TAG
            sudo docker run -d --name myappcontainer -p 80:8000 $REGISTRY/$REPOSITORY:$IMAGE_TAG
